name: PR Sanity Check
on: pull_request

jobs:

  prtest:
    name: PR sanity check
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        ./deps.sh

    - name: Run tests
      id: tests
      env:
        TRAVIS: yes
        IN_TRAVIS_CI: yes
      run: ./tests.sh
